// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID           pgtype.UUID
	Title        string
	Slug         string
	BasePriceUsd pgtype.Numeric
	Discription  pgtype.Text
	InsertedAt   pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
